# Generated by Django 2.1.7 on 2019-03-06 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtools', '0003_auto_20160128_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('picture', models.ImageField(blank=True, max_length=200, null=True, upload_to='', verbose_name='Profile Picture')),
                ('bio', models.CharField(blank=True, max_length=200, verbose_name='Short Bio')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('pobox', models.CharField(blank=True, max_length=20, verbose_name='P.O. Box')),
                ('apt_unit', models.CharField(blank=True, max_length=20, verbose_name='Apt/Unit')),
                ('street_num', models.CharField(blank=True, max_length=20, verbose_name='Street Number')),
                ('street_name', models.CharField(blank=True, max_length=50, verbose_name='Street Name')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='City/Town')),
                ('province', models.CharField(blank=True, choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NS', 'Nova Scotia'), ('NT', 'Northwest Territories'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Québec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], db_index=True, max_length=2, verbose_name='Province')),
                ('country', django_countries.fields.CountryField(default='CA', max_length=2)),
                ('post_code', models.CharField(blank=True, max_length=7, verbose_name='Postal Code')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
